# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Battleship.Api.Game do
  @moduledoc """
  API calls for all endpoints tagged `Game`.
  """

  alias Battleship.Connection
  import Battleship.RequestBuilder


  @doc """
  Initializes a game and returns a game id that you must pass to subsequent calls

  ## Parameters

  - connection (Battleship.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Battleship.Model.NewGameResponse{}} on success
  {:error, info} on failure
  """
  @spec new_game(Tesla.Env.client, keyword()) :: {:ok, Battleship.Model.NewGameResponse.t} | {:error, Tesla.Env.t}
  def new_game(connection, opts \\ []) do
    optional_params = %{
      
    }

    %{}
    |> method(:get)
    |> url("/new_game")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Battleship.Model.NewGameResponse{})
  end

  @doc """
  Submits a turn

  ## Parameters

  - connection (Battleship.Connection): Connection to server
  - body (Turn): 
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Battleship.Model.Turn{}} on success
  {:error, info} on failure
  """
  @spec turn(Tesla.Env.client, Battleship.Model.Turn.t, keyword()) :: {:ok, Battleship.Model.Turn.t} | {:error, Tesla.Env.t}
  def turn(connection, body, opts \\ []) do
    optional_params = %{
      
    }

    %{}
    |> method(:post)
    |> url("/turn")
    |> add_param(:body, :"body", body)
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Battleship.Model.Turn{})
  end
end
