# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Battleship.Model.Turn do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"game_id",
    :"response",
    :"guess"
  ]
end

defimpl Poison.Decoder, for: Battleship.Model.Turn do
  import Battleship.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"response", :struct, Battleship.Model.Response, options)
    |> deserialize(:"guess", :struct, Battleship.Model.Guess, options)
  end
end


